---
- name: Deploy vuejs frontend on all hosts
  hosts: all
  vars:
    frontend_dir: "{{ project_dir }}"
  handlers:
    - import_tasks: telescoop-deploy/handlers/nginx.yml
  tasks:
    - import_tasks: telescoop-deploy/tasks/create-https-certificate.yml
    - import_tasks: telescoop-deploy/tasks/setup-user-and-directories.yml
    - import_tasks: telescoop-deploy/tasks/setup-and-clone-git.yml
      vars:
        clone_path: "{{ frontend_dir }}"
        repo: "{{ frontend_repo }}"
        branch: "{{ frontend_branch }}"
        git_track_submodules: false
        identity_file_path: "{{ frontend_identity_file_path }}"
    # - import_tasks: telescoop-deploy/tasks/setup-node-dependencies.yml
    #   vars:
    #     current_path: "{{ frontend_dir }}"
    - name: add environment variable file
      template:
        src: frontend.env
        dest: "{{ frontend_dir }}/.env"
    - import_tasks: telescoop-deploy/tasks/build-js-app.yml
      vars:
        static_path: "{{ frontend_static_path }}"
    - import_tasks: telescoop-deploy/tasks/setup-nginx.yml
      vars:
        static_path: "{{ frontend_static_path}}"
        use_password: false
        username: duplomb
        password: laurent
        passwd_dir: "{{ frontend_dir }}"
        nginx_conf_filename: "{{ project_slug }}"
        server_uris_passed_to_backend:
          - admin
          - api
          - backup
          - hijack
          - cms
